server:
  port: 30403
spring:
  main:
    allow-bean-definition-overriding: true
  resources:
    static-locations: file:C:/workspace/leader/dist
  jpa:
    properties.hibernate.format_sql: true
    database: ORACLE
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: oracle
    url: jdbc:oracle:thin:@127.0.0.1:1521:ORCL
    username: C##scott
    password: tiger
    driverClassName: oracle.jdbc.driver.OracleDriver
    initialization-mode: always
    sql-script-encoding: utf-8
  redis:
    host: localhost
    port: 6379
  http:
    encoding.charset: UTF-8
    encoding.enabled: true
    encoding.force: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  mustache:
    suffix: .html
    thymeleaf:
      cache: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 5000MB
      max-request-size: 5000MB
  profiles:
    include: oauth
  security:
    enable-csrf: false
    oauth2:
      client:
        registration:
          kakao:
            client-id: <your id>
            client-secret: <your secret>
            redirect-uri: <your url>/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile
              - account_email
          naver:
            client-id: <your id>
            client-secret: <your secret>
            redirect-uri: <your url>/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
          google:
            client-id: <your id>
            client-secret: your secret>
            scope:
              - profile
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHN

logging:
  config: classpath:logback.xml

external:
  count: 10
  key: 01234567890123456789012345678901
  salt: 70726574657374
  temp: ./files/temps
  path: ./files/availables


